# Generated by Django 5.0.1 on 2024-01-08 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название блока')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание блока')),
                ('image', models.FileField(blank=True, null=True, upload_to='blocks', verbose_name='Изображение блока')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название виллы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание виллы')),
                ('image', models.FileField(blank=True, null=True, upload_to='villas', verbose_name='Изображение виллы')),
            ],
            options={
                'verbose_name': 'Вилла',
                'verbose_name_plural': 'Виллы',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название этажа')),
                ('image', models.FileField(blank=True, null=True, upload_to='floors', verbose_name='Изображение этажа')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='villa.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='floor',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='villa.floor', verbose_name='Этаж'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер апартамента')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название апартамента')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание апартамента')),
                ('image', models.FileField(blank=True, null=True, upload_to='apartments', verbose_name='Изображение апартамента')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продано')),
                ('sold_time', models.DateTimeField(blank=True, null=True, verbose_name='Время продажи')),
                ('square', models.FloatField(blank=True, null=True, verbose_name='Площадь')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='Количество комнат')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='villa.floor', verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Апартамент',
                'verbose_name_plural': 'Апартаменты',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='villa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='villa.villa', verbose_name='Вилла'),
        ),
    ]
