# Generated by Django 5.0.1 on 2024-01-12 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0002_remove_block_villa_remove_apartment_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='villa.floor', verbose_name='Этаж'),
        ),
    ]
