# Generated by Django 5.0.1 on 2024-01-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0003_alter_apartment_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='apartments', verbose_name='PDF файл'),
        ),
    ]
