# Generated by Django 5.0.1 on 2024-03-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0005_apartment_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='variant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вариант'),
        ),
    ]
